<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>BetterVersioning.net</PackageId>
    <Description>Convention-based from/until API versioning for ASP.NET Core.</Description>
    <IsPackable>true</IsPackable>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="\" />
    <PackageReference Include="Asp.Versioning.Mvc" />
  </ItemGroup>

</Project>